# Generated by Django 6.0.3 on 2026-03-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunioes', '0002_reuniao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniao',
            name='status',
            field=models.CharField(choices=[('AGENDADA', 'Agendada'), ('CANCELADA', 'Cancelada'), ('REALIZADA', 'Realizada')], default='AGENDADA', max_length=20),
        ),
    ]
