# Generated by Django 6.0.3 on 2026-03-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunioes', '0004_participante'),
    ]

    operations = [
        migrations.AddField(
            model_name='reuniao',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='reunioes', to='reunioes.participante'),
        ),
    ]
