# Generated by Django 6.0.3 on 2026-03-29 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunioes', '0005_reuniao_participantes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniao',
            name='titulo',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='ReuniaoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reuniao_titulo', models.CharField(max_length=150)),
                ('acao', models.CharField(choices=[('CRIACAO', 'Criação'), ('EDICAO', 'Edição'), ('CANCELAMENTO', 'Cancelamento'), ('EXCLUSAO', 'Exclusão')], max_length=20)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('reuniao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='reunioes.reuniao')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_reunioes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
