# Generated by Django 6.0.3 on 2026-04-23 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunioes', '0006_alter_reuniao_titulo_reuniaolog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participacoes_vinculadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reuniao',
            name='organizador_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reunioes_organizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reuniaolog',
            name='acao',
            field=models.CharField(choices=[('CRIACAO', 'Criacao'), ('EDICAO', 'Edicao'), ('CANCELAMENTO', 'Cancelamento'), ('EXCLUSAO', 'Exclusao')], max_length=20),
        ),
        migrations.CreateModel(
            name='ItemEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('ADM', 'Estoque ADM'), ('TI', 'Estoque TI')], max_length=3)),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('unidade_medida', models.CharField(default='un', max_length=30)),
                ('quantidade_atual', models.IntegerField(default=0)),
                ('estoque_minimo', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
                'unique_together': {('area', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saida')], max_length=10)),
                ('quantidade', models.PositiveIntegerField()),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='reunioes.itemestoque')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_estoque', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('agenda', 'Minha Agenda'), ('estoque_adm', 'Estoque ADM'), ('estoque_ti', 'Estoque TI'), ('avaliacao', 'Avaliacao de Colaboradores'), ('chamados_ti', 'Chamados - TI')], max_length=30)),
                ('titulo', models.CharField(max_length=180)),
                ('mensagem', models.TextField()),
                ('url_destino', models.CharField(blank=True, max_length=255)),
                ('lida', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('lida_em', models.DateTimeField(blank=True, null=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, max_length=120)),
                ('papel_agenda', models.CharField(choices=[('SEM_ACESSO', 'Sem acesso'), ('VISUALIZADOR', 'Visualizador'), ('SUPERVISOR', 'Supervisor'), ('ADMINISTRADOR', 'Administrador')], default='ADMINISTRADOR', max_length=20)),
                ('papel_estoque_adm', models.CharField(choices=[('SEM_ACESSO', 'Sem acesso'), ('VISUALIZADOR', 'Visualizador'), ('SUPERVISOR', 'Supervisor'), ('ADMINISTRADOR', 'Administrador')], default='SEM_ACESSO', max_length=20)),
                ('papel_estoque_ti', models.CharField(choices=[('SEM_ACESSO', 'Sem acesso'), ('VISUALIZADOR', 'Visualizador'), ('SUPERVISOR', 'Supervisor'), ('ADMINISTRADOR', 'Administrador')], default='SEM_ACESSO', max_length=20)),
                ('papel_avaliacao', models.CharField(choices=[('SEM_ACESSO', 'Sem acesso'), ('VISUALIZADOR', 'Visualizador'), ('SUPERVISOR', 'Supervisor'), ('ADMINISTRADOR', 'Administrador')], default='SEM_ACESSO', max_length=20)),
                ('papel_chamados_ti', models.CharField(choices=[('SEM_ACESSO', 'Sem acesso'), ('VISUALIZADOR', 'Visualizador'), ('SUPERVISOR', 'Supervisor'), ('ADMINISTRADOR', 'Administrador')], default='SEM_ACESSO', max_length=20)),
                ('receber_email_notificacao', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
