# Generated by Django 6.0.3 on 2026-04-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunioes', '0007_participante_usuario_reuniao_organizador_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='nivel_perfil',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('SUPERVISOR', 'Supervisor'), ('USUARIO', 'Usuario')], default='USUARIO', max_length=20),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='papel_usuarios',
            field=models.CharField(choices=[('SEM_ACESSO', 'Sem acesso'), ('VISUALIZADOR', 'Visualizador'), ('SUPERVISOR', 'Supervisor'), ('ADMINISTRADOR', 'Administrador')], default='SEM_ACESSO', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='modulo',
            field=models.CharField(choices=[('agenda', 'Minha Agenda'), ('usuarios', 'Usuarios'), ('estoque_adm', 'Estoque ADM'), ('estoque_ti', 'Estoque TI'), ('avaliacao', 'Avaliacao de Colaboradores'), ('chamados_ti', 'Chamados - TI')], max_length=30),
        ),
    ]
