# Generated by Django 6.0.3 on 2026-04-27 20:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunioes', '0008_perfilusuario_nivel_perfil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemestoque',
            name='categoria',
            field=models.CharField(choices=[('GERAL', 'Geral'), ('COPA', 'Copa'), ('EXPEDIENTE', 'Material de Expediente')], default='GERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='itemestoque',
            name='codigo_proprio',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='itemestoque',
            name='custo_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='custo_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='data_movimentacao',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='origem_externa',
            field=models.CharField(blank=True, max_length=140, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='quantidade_devolvida',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='setor',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
