# Generated by Django 6.0.3 on 2026-04-27 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunioes', '0009_itemestoque_categoria_itemestoque_codigo_proprio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='papel_rota_motoboy',
            field=models.CharField(choices=[('SEM_ACESSO', 'Sem acesso'), ('VISUALIZADOR', 'Visualizador'), ('SUPERVISOR', 'Supervisor'), ('ADMINISTRADOR', 'Administrador')], default='SEM_ACESSO', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='modulo',
            field=models.CharField(choices=[('agenda', 'Minha Agenda'), ('usuarios', 'Usuarios'), ('rota_motoboy', 'Rota do MotoBoy'), ('estoque_adm', 'Estoque ADM'), ('estoque_ti', 'Estoque TI'), ('avaliacao', 'Avaliacao de Colaboradores'), ('chamados_ti', 'Chamados - TI')], max_length=30),
        ),
        migrations.CreateModel(
            name='RotaMotoboy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('titulo', models.CharField(blank=True, max_length=150)),
                ('observacao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ROTA', 'Em rota'), ('CONCLUIDA', 'Concluida')], default='ABERTA', max_length=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotas_motoboy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RotaParada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('setor', models.CharField(blank=True, max_length=80)),
                ('empresa', models.CharField(max_length=140)),
                ('tipo_servico', models.CharField(choices=[('COLETA', 'Coleta'), ('ENTREGA', 'Entrega'), ('OUTRO', 'Outro')], default='COLETA', max_length=10)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('observacao', models.TextField(blank=True)),
                ('status_final', models.CharField(choices=[('PENDENTE', 'Pendente'), ('OK', 'OK'), ('AMANHA', 'Amanha'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='reunioes.rotamotoboy')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
