# Generated by Codex on 2026-05-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reunioes", "0010_perfilusuario_papel_rota_motoboy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemestoque",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("GERAL", "Geral"),
                    ("COPA", "Copa"),
                    ("EXPEDIENTE", "Material de Expediente"),
                    ("ESCRITORIO_TI", "Escritorio TI"),
                    ("COMPUTADOR", "Computador"),
                    ("NOTEBOOK", "Notebook"),
                    ("MONITOR", "Monitor"),
                    ("TECLADO", "Teclado"),
                    ("MOUSE", "Mouse"),
                    ("HEADSET", "Headset"),
                    ("IMPRESSORA", "Impressora"),
                    ("REDE", "Rede e Internet"),
                    ("ACESSORIO_TI", "Acessorios de TI"),
                ],
                default="GERAL",
                max_length=20,
            ),
        ),
    ]
