# Generated by Django 6.0.3 on 2026-05-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunioes', '0011_alter_itemestoque_categoria_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotamotoboy',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ROTA', 'Em rota'), ('CONCLUIDA', 'Concluida'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=15),
        ),
    ]
