# Generated by Django 6.0.3 on 2026-05-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunioes', '0012_alter_rotamotoboy_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotaparada',
            name='horario_previsto',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rotaparada',
            name='tipo_servico',
            field=models.CharField(choices=[('COLETA', 'Retirada'), ('ENTREGA', 'Entrega'), ('OUTRO', 'Outro')], default='COLETA', max_length=10),
        ),
    ]
