# Generated by Django 6.0.3 on 2026-05-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunioes', '0014_popular_salas_padrao_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniao',
            name='status',
            field=models.CharField(choices=[('AGENDADA', 'Agendada'), ('CANCELADA', 'Cancelada'), ('REALIZADA', 'Concluida')], default='AGENDADA', max_length=20),
        ),
    ]
