# Generated by Django 6.0.3 on 2026-05-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunioes', '0015_alter_reuniao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotamotoboy',
            name='distancia_total_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='rotamotoboy',
            name='duracao_total_minutos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rotamotoboy',
            name='endereco_inicio',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rotamotoboy',
            name='latitude_inicio',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='rotamotoboy',
            name='longitude_inicio',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='rotamotoboy',
            name='rota_otimizada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rotaparada',
            name='distancia_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='rotaparada',
            name='duracao_minutos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rotaparada',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='rotaparada',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
