# Generated by Django 6.0.3 on 2026-05-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunioes', '0016_rotamotoboy_distancia_total_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotamotoboy',
            name='horario_saida',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
