# Generated by Django 6.0.3 on 2026-05-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunioes', '0017_rotamotoboy_horario_saida'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='papel_estoque_expediente',
            field=models.CharField(choices=[('SEM_ACESSO', 'Sem acesso'), ('VISUALIZADOR', 'Visualizador'), ('SUPERVISOR', 'Supervisor'), ('ADMINISTRADOR', 'Administrador')], default='SEM_ACESSO', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemestoque',
            name='area',
            field=models.CharField(choices=[('ADM', 'Estoque ADM'), ('TI', 'Estoque TI'), ('EXP', 'Estoque Expediente')], max_length=3),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='modulo',
            field=models.CharField(choices=[('agenda', 'Minha Agenda'), ('usuarios', 'Usuarios'), ('rota_motoboy', 'Rota do MotoBoy'), ('estoque_adm', 'Estoque ADM'), ('estoque_ti', 'Estoque TI'), ('estoque_expediente', 'Estoque Expediente'), ('avaliacao', 'Avaliacao de Colaboradores'), ('chamados_ti', 'Chamados - TI')], max_length=30),
        ),
    ]
