# Generated by Django 6.0.3 on 2026-05-25 21:21

from django.db import migrations, models


def criar_categorias_padrao(apps, schema_editor):
    CategoriaEstoque = apps.get_model("reunioes", "CategoriaEstoque")
    categorias = {
        "ADM": [
            ("GERAL", "Geral"),
            ("COPA", "Copa"),
            ("EXPEDIENTE", "Material de Expediente"),
        ],
        "TI": [
            ("GERAL", "Geral"),
            ("ESCRITORIO_TI", "Escritorio TI"),
            ("COMPUTADOR", "Computador"),
            ("NOTEBOOK", "Notebook"),
            ("MONITOR", "Monitor"),
            ("TECLADO", "Teclado"),
            ("MOUSE", "Mouse"),
            ("HEADSET", "Headset"),
            ("IMPRESSORA", "Impressora"),
            ("REDE", "Rede e Internet"),
            ("ACESSORIO_TI", "Acessorios de TI"),
        ],
        "EXP": [
            ("GERAL", "Geral"),
            ("EXPEDIENTE", "Material de Expediente"),
        ],
    }
    for area, itens in categorias.items():
        for codigo, nome in itens:
            CategoriaEstoque.objects.get_or_create(
                area=area,
                codigo=codigo,
                defaults={"nome": nome, "ativo": True},
            )


def remover_categorias_padrao(apps, schema_editor):
    CategoriaEstoque = apps.get_model("reunioes", "CategoriaEstoque")
    CategoriaEstoque.objects.filter(
        area__in=["ADM", "TI", "EXP"],
        codigo__in=[
            "GERAL",
            "COPA",
            "EXPEDIENTE",
            "ESCRITORIO_TI",
            "COMPUTADOR",
            "NOTEBOOK",
            "MONITOR",
            "TECLADO",
            "MOUSE",
            "HEADSET",
            "IMPRESSORA",
            "REDE",
            "ACESSORIO_TI",
        ],
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('reunioes', '0018_perfilusuario_papel_estoque_expediente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemestoque',
            name='categoria',
            field=models.CharField(default='GERAL', max_length=50),
        ),
        migrations.CreateModel(
            name='CategoriaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('ADM', 'Estoque ADM'), ('TI', 'Estoque TI'), ('EXP', 'Estoque Expediente')], max_length=3)),
                ('codigo', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['area', 'nome'],
                'unique_together': {('area', 'codigo'), ('area', 'nome')},
            },
        ),
        migrations.RunPython(criar_categorias_padrao, remover_categorias_padrao),
    ]
