# Generated by Django 6.0.3 on 2026-05-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunioes', '0019_alter_itemestoque_categoria_categoriaestoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='funcao',
            field=models.CharField(blank=True, choices=[('ESTAGIARIO', 'Estagiario'), ('ASSISTENTE', 'Assistente'), ('ANALISTA', 'Analista'), ('SUPERVISOR', 'Supervisor'), ('GERENTE', 'Gerente'), ('DIRETOR', 'Diretor'), ('ADMINISTRADOR', 'Administrador')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='setor',
            field=models.CharField(blank=True, choices=[('CONTABIL', 'Contabil'), ('FISCAL', 'Fiscal'), ('PESSOAL', 'Pessoal'), ('EMPRESARIAL', 'Empresarial'), ('COMERCIAL', 'Comercial'), ('TI', 'TI'), ('RECEPCAO', 'Recepcao'), ('FINANCEIRO', 'Financeiro')], default='', max_length=20),
        ),
    ]
