# Generated by Codex on 2026-06-18

from django.db import migrations, models


def preencher_destino_com_partida(apps, schema_editor):
    RotaMotoboy = apps.get_model("reunioes", "RotaMotoboy")
    for rota in RotaMotoboy.objects.filter(endereco_destino=""):
        rota.endereco_destino = rota.endereco_inicio
        rota.save(update_fields=["endereco_destino"])


class Migration(migrations.Migration):

    dependencies = [
        ("reunioes", "0020_perfilusuario_funcao_perfilusuario_setor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participante",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="rotamotoboy",
            name="endereco_destino",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="rotamotoboy",
            name="latitude_destino",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="rotamotoboy",
            name="longitude_destino",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.RunPython(preencher_destino_com_partida, migrations.RunPython.noop),
    ]
