# Generated by Django 6.0.3 on 2026-07-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunioes', '0021_rotamotoboy_destino_final'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnderecoEmpresaMotoboy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=140, unique=True)),
                ('endereco', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='participante',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
